// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC14niAJbaXqX2TmIYMCVxeecdi2kSQp9o',
    appId: '1:266303460572:web:3ac9855499f9bb5f7bd019',
    messagingSenderId: '266303460572',
    projectId: 'myreactapp-81c10',
    authDomain: 'myreactapp-81c10.firebaseapp.com',
    storageBucket: 'myreactapp-81c10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForAndroid',
    appId: '1:123456789:android:demo',
    messagingSenderId: '123456789',
    projectId: 'perplexity-clone-demo',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForIOS',
    appId: '1:123456789:ios:demo',
    messagingSenderId: '123456789',
    projectId: 'perplexity-clone-demo',
    iosBundleId: 'com.example.perplexityClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForMacOS',
    appId: '1:123456789:macos:demo',
    messagingSenderId: '123456789',
    projectId: 'perplexity-clone-demo',
    iosBundleId: 'com.example.perplexityClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForWindows',
    appId: '1:123456789:windows:demo',
    messagingSenderId: '123456789',
    projectId: 'perplexity-clone-demo',
  );
}